In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df =pd.read_csv("customer_data.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  100000 non-null  int64
 1   age                 100000 non-null  int64
 2   gender              100000 non-null  object
 3   income              100000 non-null  int64
 4   education           100000 non-null  object
 5   region              100000 non-null  object
 6   loyalty_status      100000 non-null  object
 7   purchase_frequency  100000 non-null  object
 8   purchase_amount     100000 non-null  int64
 9   product_category    100000 non-null  object
 10  promotion_usage     100000 non-null  int64
 11  satisfaction_score  100000 non-null  int64
dtypes: int64(6), object(6)
memory usage: 9.2+ MB

In [5]:
df.duplicated().sum()
df.describe()

,id,age,income,purchase_amount,promotion_usage,satisfaction_score
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,50000.500000,30.003260,27516.269880,9634.790840,0.300800,5.009650
std,28867.657797,4.480535,12996.782587,4799.339449,0.458608,1.038714
min,1.000000,12.000000,5000.000000,1118.000000,0.000000,0.000000
25%,25000.750000,27.000000,16271.750000,5583.000000,0.000000,4.000000
50%,50000.500000,30.000000,27584.500000,9452.000000,0.000000,5.000000
75%,75000.250000,33.000000,38747.250000,13350.000000,1.000000,6.000000
max,100000.000000,49.000000,50000.000000,26204.000000,1.000000,10.000000

In [6]:
# Create Age Groups

bins = [0, 25, 35, 45, 55, 100]
labels = ['18-25', '26-35', '36-45', '46-55', '56+']

df['age_group'] = pd.cut(
    df['age'],
    bins=bins,
    labels=labels
)

print(df['age_group'].value_counts().sort_index())

age_group
18-25    15746
26-35    73333
36-45    10894
46-55       27
56+          0
Name: count, dtype: int64

In [7]:
# Spending by Age Group

age_spending = df.groupby(
    'age_group',
    observed=True
)['purchase_amount'].agg(['mean', 'sum'])

age_spending

                  mean        sum
age_group
18-25      9632.499809  151673342
26-35      9630.939972  706265721
36-45      9663.913530  105278674
46-55      9679.518519     261347

In [ ]:


frequency_counts = df['purchase_frequency'].value_counts()

print("Purchase Frequency:")
print(frequency_counts)

Purchase Frequency:
purchase_frequency
rare          50019
occasional    29886
frequent      20095
Name: count, dtype: int64

In [ ]:


frequency_spending = df.groupby(
    'purchase_frequency'
)['purchase_amount'].agg(['count', 'mean', 'sum'])

frequency_spending

                    count         mean        sum
purchase_frequency
frequent            20095  9616.911371  193251834
occasional          29886  9661.649870  288748068
rare                50019  9625.925788  481479182

In [ ]:
# most purchased data

category_counts = df['product_category'].value_counts()

print("Number of purchases by product category:")
print(category_counts)

Number of purchases by product category:
product_category
Electronics    30027
Clothing       19989
Books          14925
Food           14822
Health         10123
Home            5079
Beauty          5035
Name: count, dtype: int64

In [12]:
# Total and average spending by product category

category_spending = df.groupby(
    'product_category'
)['purchase_amount'].agg(['count', 'mean', 'sum'])

category_spending

                  count         mean        sum
product_category
Beauty             5035  9721.366038   48947078
Books             14925  9592.935678  143174565
Clothing          19989  9634.595327  192585926
Electronics       30027  9648.226696  289707303
Food              14822  9669.953110  143328045
Health            10123  9610.963647   97291785
Home               5079  9538.173262   48444382

In [14]:
# Loyalty Status Analysis

loyalty_analysis = df.groupby(
    'loyalty_status'
)['purchase_amount'].agg(['count', 'mean', 'sum'])

loyalty_analysis

                count         mean        sum
loyalty_status
Gold             9898  9621.487573   95233484
Regular         60138  9639.976537  579728909
Silver          29964  9628.777566  288516691

In [15]:
# Promotion Usage Analysis

promotion_analysis = df.groupby(
    'promotion_usage'
)['purchase_amount'].agg(['count', 'mean', 'sum'])

promotion_analysis

                 count         mean        sum
promotion_usage
0                69920  9631.150901  673410071
1                30080  9643.251762  290069013